vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        homePage:
            uri_prefix: /images/homePage
            upload_destination: '%kernel.project_dir%/public/images/homePage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
